---

- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers
  become: true
  gather_facts: false
  collections:
    - community.postgresql
  tags:
    - database_servers

  roles:
  
    - postgres
